### ISSUE TITLE
Corrupt weights file

### ISSUE THREAD

**Issue by jclarkk** [murphylmf/M-LRM#2] opened 2024-12-04 07:57 UTC
Hey,

Thanks a lot for releasing the code!

I've tried running but I'm getting the following exception:
```
Traceback (most recent call last):
  File "/mnt/c/Users/jonathan/Dev/M-LRM/infer.py", line 151, in <module>
    system = find_class(cfg.system_cls)(cfg.system)
  File "/mnt/c/Users/jonathan/Dev/M-LRM/lrm/utils/base.py", line 124, in init
    state_dict = load_module_weights(
  File "/mnt/c/Users/jonathan/Dev/M-LRM/lrm/utils/misc.py", line 41, in load_module_weights
    ckpt = torch.load(path, map_location=map_location)
  File "/home/jonathan/anaconda3/envs/mlrm/lib/python3.10/site-packages/torch/serialization.py", line 1326, in load
    with openzipfile_reader(opened_file) as opened_zipfile:
  File "/home/jonathan/anaconda3/envs/mlrm/lib/python3.10/site-packages/torch/serialization.py", line 671, in init
    super().init(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

This seems to happen when the model file is incomplete or corrupt.

Would it be possible to re-upload the weights?

Thanks!

**Comment by murphylmf** [comment] 2024-12-04 18:26
Thank you! The problem is fixed now. You can download the updated weights with the same url.

**Closed as completed by murphylmf** 2024-12-04 18:26 UTC
